### ISSUE TITLE
The datasette install plugin command gets the wrong version installed

### ISSUE THREAD

**Issue by kevin-ng** [simonw/datasette-render-images#10]
I am referring to the plugin "datasette-render-images" in particular but I think it happens to plugin "datasette-render-binary" as well.

In both cases, the error message was 

"module 'jinja2' has no attribute 'Markup' "

The error arise because of these lines in  datasette_render_images.py
```
    # Render as a data-uri
    return jinja2.Markup(
        '<img src="data:image/{};base64,{}" alt="">'.format(
            image_type, base64.b64encode(value).decode("utf8")
        )
    )
```
But in github repository the code is different and is functional
```
 # Render as a data-uri
    return Markup(
        '<img src="data:image/{};base64,{}" alt="">'.format(
            image_type, base64.b64encode(value).decode("utf8")
        )
    )
```
so if I checkout from github this plugin will work, but no if install as documented.

**Comment by kevin-ng** [comment]
The "datasette plugins" command give the following output:

```
  {
        "name": "datasette-render-images",
        "static": false,
        "templates": false,
        "version": "0.3.2",
        "hooks": [
            "render_cell"
        ]
        }
    ```
which suggest the version installed is 0.3.2, which is also the latest version released on gitgub.

**Comment by kevin-ng** [comment]
So literally I  should say the version is correct (0.3.2) but code installed is different to that released.

**Comment by msaktor** [comment]
Same issue here, could you please release the latest `main` @simonw ? Thank you the plugin is great.

**Comment by simonw** [comment]
This is fixed now. https://github.com/simonw/datasette-render-images/releases/tag/0.4
