### ISSUE TITLE
Please publish a release

### ISSUE THREAD

**Issue by DeNeutoy** [simonw/datasette-render-images#13]
Hi Simon,

Would you be able to publish a release of this package that includes this commit:

https://github.com/simonw/datasette-render-images/commit/f03e193c60eabcd14c128cb54d6030f81a2c0712

As Jinja is unpinned above 3.1 in the main `datasette` package, this plugin breaks when installed during `datsette publish/package`, as the deprecation warnings that were fixed in the above commit are now hard errors.

Thanks!

**Comment by DeNeutoy** [comment]
To reproduce:

```
sqlite-utils insert-files test.db images ./some/images/

# Running this image fails if you navigate to a page that requires the dataset-render-images plugin to run
datasette package --install datasette-render-images --tag failing-image test.db 

# Succeeds, as <3.1 does not have backward incompatible api changes with the released version of datasette-render-images
datasette package --install datasette-render-images --install "'jinja2<3.1'" --tag successful-image test.db

```

**Comment by simonw** [comment]
https://github.com/simonw/datasette-render-images/releases/tag/0.4
